name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessário para ver o histórico todo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # ajusta à versão de Go que usas

      - name: Generate semantic version
        id: semver
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.semver.outputs.version_tag }}"
          git push origin "${{ steps.semver.outputs.version_tag }}"

      - name: Build minifyx for multiple platforms
        run: |
          VERSION=${{ steps.semver.outputs.version_tag }}
          mkdir -p dist

          LDFLAGS="-X github.com/pinjoa/minifyx/minifier.Version=${VERSION}"

          # Linux
          GOOS=linux GOARCH=amd64 go build \
            -ldflags "${LDFLAGS}" \
            -o dist/minifyx-${VERSION}-linux-amd64 ./cmd/minifyx

          # Linux arm64
          GOOS=linux GOARCH=arm64 go build \
            -ldflags "${LDFLAGS}" \
            -o dist/minifyx-${VERSION}-linux-arm64 ./cmd/minifyx

          # Windows
          GOOS=windows GOARCH=amd64 go build \
            -ldflags "${LDFLAGS}" \
            -o dist/minifyx-${VERSION}-windows-amd64.exe ./cmd/minifyx

          # macOS (darwin)
          GOOS=darwin GOARCH=amd64 go build \
            -ldflags "${LDFLAGS}" \
            -o dist/minifyx-${VERSION}-darwin-amd64 ./cmd/minifyx

          # macOS (darwin)
          GOOS=darwin GOARCH=arm64 go build \
            -ldflags "${LDFLAGS}" \
            -o dist/minifyx-${VERSION}-darwin-arm64 ./cmd/minifyx

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.version_tag }}
          name: ${{ steps.semver.outputs.version_tag }}
          generate_release_notes: true
          files: dist/*
