name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessário para ver o histórico todo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # ajusta à versão de Go que usas

      - name: Generate semantic version
        id: semver
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.semver.outputs.version_tag }}"
          git push origin "${{ steps.semver.outputs.version_tag }}"

      - name: Build minifyx with version
        run: |
          VERSION=${{ steps.semver.outputs.version_tag }}
          go build -ldflags "\
            -X 'github.com/pinjoa/minifyx.Version=${VERSION}' \
            -X 'github.com/pinjoa/minifyx/cmd/minifyx.version=${VERSION}'" \
            -o minifyx ./cmd/minifyx

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.version_tag }}
          name: ${{ steps.semver.outputs.version_tag }}
          generate_release_notes: true
          files: |
            minifyx
